/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.Actividad;
import clases.Robot;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author danie
 */
public class VentanaAlgoritmos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAlgoritmos
     */
    public VentanaAlgoritmos() {
        initComponents();
        setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListEntrada = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListEntradaOrdenada = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListAlgoritmo1Problema1Variante = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListAlgoritmo2Problema1 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListAlgoritmo3Problema1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListAlgoritmo1Problema1 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        lblAlgoritmo1Problema1 = new javax.swing.JLabel();
        lblEntradaOrdenadaTime = new javax.swing.JLabel();
        lblAlgoritmo1Problema1Variante = new javax.swing.JLabel();
        lblAlgoritmo2Problema1 = new javax.swing.JLabel();
        lblAlgoritmo3Problema1 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jListAlgoritmo1Problema2 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jListAlgoritmo2Problema2 = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        lblAlgoritmo1Problema2 = new javax.swing.JLabel();
        lblAlgoritmo2Problema2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ProyectoLunaDiazCortezPerez");
        setPreferredSize(new java.awt.Dimension(1300, 900));

        jListEntrada.setEnabled(false);
        jListEntrada.setSelectionBackground(new java.awt.Color(238, 238, 238));
        jScrollPane1.setViewportView(jListEntrada);

        jLabel1.setText("Lista de Entradas Cargadas");

        jListEntradaOrdenada.setEnabled(false);
        jListEntradaOrdenada.setSelectionBackground(new java.awt.Color(238, 238, 238));
        jScrollPane2.setViewportView(jListEntradaOrdenada);

        jListAlgoritmo1Problema1Variante.setEnabled(false);
        jListAlgoritmo1Problema1Variante.setSelectionBackground(new java.awt.Color(238, 238, 238));
        jScrollPane3.setViewportView(jListAlgoritmo1Problema1Variante);

        jListAlgoritmo2Problema1.setEnabled(false);
        jListAlgoritmo2Problema1.setSelectionBackground(new java.awt.Color(238, 238, 238));
        jScrollPane4.setViewportView(jListAlgoritmo2Problema1);

        jListAlgoritmo3Problema1.setEnabled(false);
        jListAlgoritmo3Problema1.setSelectionBackground(new java.awt.Color(238, 238, 238));
        jScrollPane5.setViewportView(jListAlgoritmo3Problema1);

        jLabel2.setText("Entrada Organizada");

        jLabel3.setText("Algoritmo 1 Problema 1 Variante");

        jLabel4.setText("Algoritmo 2 Problema 1");

        jLabel5.setText("Algoritmo 3 Problema 1");

        jListAlgoritmo1Problema1.setEnabled(false);
        jListAlgoritmo1Problema1.setSelectionBackground(new java.awt.Color(238, 238, 238));
        jScrollPane6.setViewportView(jListAlgoritmo1Problema1);

        jLabel6.setText("Algoritmo 1 Problema 1");

        lblAlgoritmo1Problema1.setText("Time(ms): ");

        lblEntradaOrdenadaTime.setText("Time(ms): ");

        lblAlgoritmo1Problema1Variante.setText("Time(ms): ");

        lblAlgoritmo2Problema1.setText("Time(ms): ");

        lblAlgoritmo3Problema1.setText("Time(ms): ");

        jListAlgoritmo1Problema2.setEnabled(false);
        jListAlgoritmo1Problema2.setSelectionBackground(new java.awt.Color(238, 238, 238));
        jScrollPane7.setViewportView(jListAlgoritmo1Problema2);

        jLabel7.setText("Algoritmo 1 Problema 2");

        jListAlgoritmo2Problema2.setEnabled(false);
        jListAlgoritmo2Problema2.setSelectionBackground(new java.awt.Color(238, 238, 238));
        jScrollPane8.setViewportView(jListAlgoritmo2Problema2);

        jLabel8.setText("Algoritmo 2 Problema 2");

        lblAlgoritmo1Problema2.setText("Time(ms): ");

        lblAlgoritmo2Problema2.setText("Time(ms): ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblAlgoritmo1Problema1))
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblAlgoritmo1Problema2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel7)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblAlgoritmo1Problema1Variante))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEntradaOrdenadaTime)
                                    .addComponent(lblAlgoritmo2Problema2)
                                    .addComponent(lblAlgoritmo2Problema1))))
                        .addGap(40, 40, 40)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblAlgoritmo3Problema1)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEntradaOrdenadaTime)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlgoritmo1Problema1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlgoritmo2Problema1)
                            .addComponent(lblAlgoritmo1Problema1Variante))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblAlgoritmo3Problema1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlgoritmo2Problema2)
                    .addComponent(lblAlgoritmo1Problema2))
                .addGap(120, 120, 120))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setup(){
        //setList();
    }
    
    public void setJListEntrada(List<Actividad> lista){
       DefaultListModel dlm = new DefaultListModel();
       lista.forEach(actividad -> {
           dlm.addElement(actividad);
        });
       jListEntrada.setModel(dlm);
    }
    
    public void setJListEntradaOrdenada(List<Actividad> lista, long time){
       DefaultListModel dlm = new DefaultListModel();
       lista.forEach(actividad -> {
           dlm.addElement(actividad);
        });
       jListEntradaOrdenada.setModel(dlm);
       lblEntradaOrdenadaTime.setText("Tiempo(ms): " + Long.toString(time));
    }
    
    public void setJListAlgoritmo1Problema1(Robot robot, long time){
       DefaultListModel dlm = new DefaultListModel();
       robot.getActividades().forEach(actividad -> {
           dlm.addElement(actividad);
        });
       jListAlgoritmo1Problema1.setModel(dlm);
       lblAlgoritmo1Problema1.setText("<html>Tiempo(ms): " + Long.toString(time) + "<br/>Horas total: " + robot.getHorasTotal() + "</html>");
    }
    
    public void setJListAlgoritmo1Problema1Variante(Robot robot, long time){
       DefaultListModel dlm = new DefaultListModel();
       robot.getActividades().forEach(actividad -> {
           dlm.addElement(actividad);
        });
       jListAlgoritmo1Problema1Variante.setModel(dlm);
       lblAlgoritmo1Problema1Variante.setText("<html>Tiempo(ms): " + Long.toString(time) + "<br/>Horas total: " + robot.getHorasTotal() + "</html>");
    }
    
    public void setJListAlgoritmo2Problema1(Robot robot, long time){
       DefaultListModel dlm = new DefaultListModel();
       robot.getActividades().forEach(actividad -> {
           dlm.addElement(actividad);
        });
       jListAlgoritmo2Problema1.setModel(dlm);
       lblAlgoritmo2Problema1.setText("<html>Tiempo(ms): " + Long.toString(time) + "<br/>Horas total: " + robot.getHorasTotal() + "</html>");
    }
    
    public void setJListAlgoritmo3Problema1(Robot robot, long time){
       DefaultListModel dlm = new DefaultListModel();
       robot.getActividades().forEach(actividad -> {
           dlm.addElement(actividad);
        });
       jListAlgoritmo3Problema1.setModel(dlm);
       lblAlgoritmo3Problema1.setText("<html>Tiempo(ms): " + Long.toString(time) + "<br/>Horas total: " + robot.getHorasTotal() + "</html>");
    }
    
    public void setJListAlgoritmo1Problema2(Robot robot, long time){
       DefaultListModel dlm = new DefaultListModel();
       robot.getActividades().forEach(actividad -> {
           dlm.addElement(actividad);
        });
       jListAlgoritmo1Problema2.setModel(dlm);
       lblAlgoritmo1Problema2.setText("<html>Tiempo(ms): " + Long.toString(time) + "<br/>Cantidad actividades: " + robot.getCantidadActividades()+ "<br/>Horas total: " + robot.getHorasTotal() + "</html>");
    }
    
    public void setJListAlgoritmo2Problema2(Robot robot, long time){
       DefaultListModel dlm = new DefaultListModel();
       robot.getActividades().forEach(actividad -> {
           dlm.addElement(actividad);
        });
       jListAlgoritmo2Problema2.setModel(dlm);
       lblAlgoritmo2Problema2.setText("<html>Tiempo(ms): " + Long.toString(time) + "<br/>Cantidad actividades: " + robot.getCantidadActividades()+ "<br/>Horas total: " + robot.getHorasTotal() + "</html>");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAlgoritmos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAlgoritmos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAlgoritmos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAlgoritmos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAlgoritmos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jListAlgoritmo1Problema1;
    private javax.swing.JList<String> jListAlgoritmo1Problema1Variante;
    private javax.swing.JList<String> jListAlgoritmo1Problema2;
    private javax.swing.JList<String> jListAlgoritmo2Problema1;
    private javax.swing.JList<String> jListAlgoritmo2Problema2;
    private javax.swing.JList<String> jListAlgoritmo3Problema1;
    private javax.swing.JList<String> jListEntrada;
    private javax.swing.JList<String> jListEntradaOrdenada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lblAlgoritmo1Problema1;
    private javax.swing.JLabel lblAlgoritmo1Problema1Variante;
    private javax.swing.JLabel lblAlgoritmo1Problema2;
    private javax.swing.JLabel lblAlgoritmo2Problema1;
    private javax.swing.JLabel lblAlgoritmo2Problema2;
    private javax.swing.JLabel lblAlgoritmo3Problema1;
    private javax.swing.JLabel lblEntradaOrdenadaTime;
    // End of variables declaration//GEN-END:variables
}
